version: 2

models:
  - name: fct_monthly_company_spend
    description: Monthly aggregated spend per company
    columns:
      - name: company_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: total_spend_usd
      - name: transaction_count

  - name: fct_daily_outstanding_balance
    description: Daily outstanding balance per company
    columns:
      - name: company_id
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: outstanding_balance_usd
    tests:
      - unique:
          combination_of:
            - company_id
            - date
